config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'signup' => 'users#new'
  post 'signup' => 'users#create'
  get 'login'   => 'sessions#new'
  post 'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get '/words/new' => 'words#new'

  get "/auth/google/callback" => 'sessions#create'
  get "/auth/failure" => redirect('/')  ##, to:
  get "/users/user_with_most_words" => 'users#user_with_most_words'

  resources :users do
    resources :words, only: [:index, :new, :create, :show]
  end
  resources :words do
    resources :word_feelings, only: [:new, :create]
  end
  resources :words, only: [:index, :show]
  resources :feelings, only: [:index, :show]

end

app/models/word.rb
require 'pry'
class Word < ApplicationRecord
  belongs_to :user
  has_many :word_feelings
  has_many :feelings, through: :word_feelings
  accepts_nested_attributes_for :word_feelings
  validates :entry, presence: true, format: { with: /(^[-a-zA-Z]+(\s+[-a-zA-Z]+)*$)/i, message: "cannot begin or end with spaces, and cannot contain numbers or special characters."}
  validates_uniqueness_of :entry, :case_sensitive => false, :message=>"is already in the database."
  scope :most_recent, -> (limit) { order("created_at desc").limit(limit) }

  ##return word IDs (not indices) of array of words
  ##after sorting alphabetically.
  def self.alphabetize_words_ids(words)
    @word_ids_abc = []
    ##indices of words array after sorting alphabetically:
    @indices = words.pluck(:entry).map.with_index.sort_by{|x| x.first.downcase}.map(&:last)
    ##words array, sorted alphabetically:
    @words_abc = @indices.map { |index| words[index] }
    ##return just the word IDs of abc-sorted words array:
    @words_abc.each do |w|
      @word_ids_abc << w.id
    end
    @word_ids_abc
  end

end

app/controllers/words_controller.rb
require 'pry'
class WordsController < ApplicationController
include WordsHelper

def words_
  if current_user
    User.find(current_user.id).words
  end
end

  def index
    if logged_in?
      @user = current_user
      ##user-added words only!
      @userwords = words_ ##see words_ method above; specific to user
      @recent_words = @userwords.most_recent(5)
    end
    ##all words
    @words_ = Word.all
    @abcwords_ids = Word.alphabetize_words_ids(@words_)
  end

  def show
    @user = current_user
    @word = Word.find_by(id: params[:id])
    @feelings = Feeling.all
    @feels = []
    @avgs = []
    @medians = []
    Feeling.all.sort_by(&:name).each do |feel|
	     @feels << feel.name
       @avgs << compute_avg(@word,feel)
       @medians << compute_median(@word,feel)
    end
    @num_users = WordFeeling.where(word_id:@word.id).distinct.pluck(:user_id).length
  end

  def new
    @word = Word.new(user_id: current_user.id)##
    @feelings = Feeling.all
  end

  def create
    user = current_user
    @word = Word.new(word_params)
    @feelings = Feeling.all
    if @word.save
      @feelings.each do |feel|
        WordFeeling.create(user_id: params[:word][:user_id], feeling_id: feel.id, word_id: @word.id, feeling_rating: params[feel.name][:feeling_rating].to_f)
      end
      redirect_to user_word_path(user, @word)
    else
      render :new
    end
  end

  def edit
    if params[:user_id]
      user = User.find_by(id: params[:user_id])
      if user.nil?
        redirect_to users_path, alert: "User not found."
      else
        @word = user.words.find_by(id: params[:id])
        redirect_to user_words_path(user), alert: "Word not found." if @word.nil?
      end
    else
      @word = Word.find(params[:id])
    end
  end

  def update
    user = current_user
    @word = Word.find_by(id: params[:id])
    if !@word.errors.full_messages.empty?
      flash[:notice] = "That word is already in the database"
      redirect_to words_path
    end
    @word.update(word_params)
    redirect_to user_word_path(user, @word)
  end

  private

  def word_params
    params.require(:word).permit(:entry, :user_id, feeling_ids:[], word_feelings_attributes: [:id, :feeling_rating])
  end

end

app/helpers/words_helper.rb
module WordsHelper

  def create_day(word)
    word.created_at.strftime("%B %d, %Y")
  end

  def create_time(word)
    word.created_at.strftime("%I:%M %p")
  end

  def compute_avg(word,feeling)
    ##compute average FOR A SINGLE FEELING FOR A SINGLE WORD.
    myword = WordFeeling.where(word_id: word.id, feeling_id: feeling.id)
    myword.average(:feeling_rating).round(2)
  end

  def compute_median(word,feeling)
    ##find median FOR A SINGLE FEELING FOR A SINGLE WORD.
    myword = WordFeeling.where(word_id: word.id, feeling_id: feeling.id)
    rating_arr = myword.pluck(:feeling_rating)
    sorted = rating_arr.sort
    len = sorted.length
    (sorted[(len - 1) / 2] + sorted[len / 2]) / 2.0
  end

  ##checks to see if current user has already ranked a word in db.
  def already_ranked?(word,user)
    WordFeeling.where(word_id: word.id, user_id: user.id).exists?
  end

  ##returns links for words starting with letter (see words index view <a> tag)
  def returnURLs(letter)
    @myErb = []
    @words_.select { |word| word.entry.upcase.start_with?(letter) }.each do |w|
      @myErb.push(link_to w.entry, @words_.find(w.id))
    end
    @myErb
  end

end

app/views/words/_form.html.erb
<%= form_for(@word) do |f| %>
  <label>Word:</label><br>
  <%= f.hidden_field :user_id %>
  <%= f.text_field :entry %><br>

  <label>How does it rank for each of these emotions?</label><br>
  <%@feelings.sort_by(&:name).each do |feel|%>
    <label><%=link_to feel.name, feel%></label><br>
    <%= range_field(feel.name, :feeling_rating, in: 1..9, step: 0.1) %><br>
  <%end%>

  <%= f.submit action_name == 'edit' ? 'Update Word' : 'New Word'%>
<% end %>

app/views/words/_pagination.js.erb
<script>
  //This block adapted from https://codepen.io/wouterbles/pen/gpaMRd
  $('.pagination-inner a').on('click', function() {
    $(this).siblings().removeClass('pagination-active');
    $(this).addClass('pagination-active');
  })

  //Words starting with T are displayed when words index loads.
  document.getElementById("list_words").addEventListener("load", makeList(<%="T"%>));

  //Display list of word links for a letter (A-Z) in innerHTML of words index "list_words" div.
  function makeList(myData){
    let myList = document.getElementById("list_words");
    //If there are words...
    if (myData.dataset.display_words.length > 2) {
      //...convert string to array: replace escaped double quotes with single quotes, replace brackets and remaining quotes, split by commas
      let myArray = myData.dataset.display_words.replace(/\\\"/g,"\'").replace(/[\[\]"]+/g,"").split(",");
      const n = (myArray.length);
      let myLIs="";
      //...create a list item for each word
      for(i = 0; i <= (n-1); i++){
        let list = myArray[i];
        myLIs += "<li>" + list + "</li>"
      }
      //...and display the words in an unordered list.
      myList.innerHTML =
      "<ul class='word_list'>" + myLIs + "</ul>";
    }
    //If no words for letter, leave a note.
    else{
      let myLetter = myData.dataset.use_letter;
      myList.innerHTML = "<p> No one has added any words starting with " + myLetter + ".</p>";
    }
  }
</script>

app/views/words/_spider.js.erb
<script>
var ctx = document.getElementById('spider').getContext('2d');
var spider = new Chart(ctx, {
    type: 'radar',
    data: {
        labels: <%=raw @feels%>,
        datasets: [{
          label: 'average rating',
          backgroundColor: "rgba(220,0,115,0.4)",
          borderColor: "rgba(220,0,115,0.2)",
          pointBackgroundColor: "rgba(220,0,115,0.4)",
          pointBorderColor: "rgba(220,0,115,0.4)",
          data: <%=@avgs%>
          }, {
          label: 'median rating',
          backgroundColor: "rgba(245,183,0,0.4)",
          borderColor: "rgba(245,183,0,0.2)",
          pointBackgroundColor: "rgba(245,183,0,0.2)",
          pointBorderColor: "rgba(245,183,0,0.2)",
          data: <%=@medians%>
        }]
    },
    options: {
        //responsive: true,
        maintainAspectRatio: false,
        scale: {
            angleLines: {
                display: false
            },
            ticks: {
                suggestedMin: 0,
                suggestedMax: 9,
            },
            pointLabels: {
              fontSize: 18
            }
        },
      //display legend or not
      legend: {
        display: true
      },
      tooltips: {
        callbacks: {
          label: function(tooltipItem) {
            return tooltipItem.yLabel;
          }
        }
      }
    }
});
</script>

app/views/words/edit.html.erb
<%if @word.errors%>
  <%@word.errors.full_messages.each do |m|%>
  <%=m%>
  <%end%>
<%end%>
<%=flash.notice %>
<%= render "form" %>

app/views/words/index.html.erb
<%=flash.notice %>

<%if logged_in?%>
  <h3>Hi <%=@user.first_name%>,</h3>
  <h3>See a word missing from the database below?</h3>
  <h3><%=link_to "Add it now!", new_user_word_path(@user), class: "link_to"%></h3>
  <br/>
  <%if @recent_words.length > 0%>
    <h3>My most recently added words</h3>
    <ul>
      <%@recent_words.each do |r|%>
      <li><%=link_to r.entry, r%> <br>
          added <%=create_day(r)%>, at <%=create_time(r)%>
      <%end%>
      </li>
    </ul>
    <br/>
    <h5>Click on a word to view or rank its emotional loadings.</h5>
  <%end%>
<%else%>
  <h3>Hi friend,</h3>
  <h3>See a word missing from the database below?</h3>
  <h3><%=link_to "Log in", login_path%> to add a word!</h3>
  <br/>
  <h5>Click on a word to view its emotional loadings.</h5>
<%end%>

<div class="container">
  <nav class="pagination-container">
      <ul class="pagination">
        <span class="pagination-inner">
        <%("A".."Z").each do |t| %>
          <a href="#" class="<%='pagination-active' if t == 'T'%>" onclick="makeList(<%=t%>);return false;"  id=<%=t%> data-display_words='<%=returnURLs(t)%>' data-use_letter=<%=t%>><%=t%></a>
        <%end%>
      </span>
      </ul>
  </nav>
  <div class="card">
    <div class="card-body" id="list_words">
    </div>
  </div>
</div>

<%= render :partial => 'words/pagination.js' %>

app/views/words/new.html.erb
<%if @word.errors%>
  <%@word.errors.full_messages.each do |m|%>
  <%=m%>
  <%end%>
<%end%>
<%=flash.notice %>
<%= render "form" %>

app/views/words/show.html.erb
<h2><%=@word.entry%></h2>
<%if logged_in? && already_ranked?(@word,@user)%>
  <h4>Congrats, you have already ranked this word.</h4>
<%elsif logged_in?%>
  <h4>Help us by <%=link_to "ranking this word", new_word_word_feeling_path(@word)%>!</h4>
<%else%>
  <h4><%=link_to "Log in", login_path%> to rank this word!</h4>
<%end%>
<br/>
<h5>Loadedness of eight emotions based on <%=@num_users%> users</h5>
<p>Users rank words on a sliding scale from 1 to 9 (with .1 intervals) for each of the emotions on the chart.</p>
<div class="card">
    <div class="card-body" style="height: 400px;">
      <canvas id="spider"></canvas>
    </div>
</div>
<%= render :partial => "words/spider.js" %>