config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'signup' => 'users#new'
  post 'signup' => 'users#create'
  get 'login'   => 'sessions#new'
  post 'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get '/words/new' => 'words#new'

  get "/auth/google/callback" => 'sessions#create'
  get "/auth/failure" => redirect('/')  ##, to:
  get "/users/user_with_most_words" => 'users#user_with_most_words'

  resources :users do
    resources :words, only: [:index, :new, :create, :show]
  end
  resources :words do
    resources :word_feelings, only: [:new, :create]
  end
  resources :words, only: [:index, :show]
  resources :feelings, only: [:index, :show]

end

app/models/word_feeling.rb
class WordFeeling < ApplicationRecord
  belongs_to :words
  belongs_to :feelings
  belongs_to :users
end

app/controllers/word_feelings_controller.rb
class WordFeelingsController < ApplicationController

  def new
    user = current_user
    @word = Word.find_by(id: params[:word_id])
    @feelings = Feeling.all##
    @word_feelings = WordFeeling.all
    @feelings.each do |feel|
        WordFeeling.new()
    end
  end

  def create
    user = current_user
    @word = Word.find_by(id: params[:word_id])
    @feelings = Feeling.all
    @word_feelings = WordFeeling.all
    @feelings.each do |feel|
      WordFeeling.create(word_id: @word.id, user_id: user.id, feeling_id: feel.id, feeling_rating: params[feel.name][:feeling_rating].to_f)
    end
    redirect_to words_path
  end

  private

end

app/views/word_feelings/_form.html.erb
<h2><%=@word.entry%></h2>
<%= form_with url: word_word_feelings_path(@word) do |f| %>

  <label>How does it rank for each of these emotions?</label><br>
  <%@feelings.sort_by(&:name).each do |feel|%>
    <label><%=link_to feel.name, feel%></label><br>
    <%= range_field(feel.name, :feeling_rating, in: 1..9, step: 0.1) %><br>
  <%end%>

  <%= f.submit action_name == 'new' ? 'Rank Word' : 'Update Word'%>
<% end %>

app/views/word_feelings/new.html.erb
<%if @word.errors%>
  <%@word.errors.full_messages.each do |m|%>
  <%=m%>
  <%end%>
<%end%>
<%params[:myword] = @word%>
<%=flash.notice %>
<%= render "form" %>