config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'signup' => 'users#new'
  post 'signup' => 'users#create'
  get 'login'   => 'sessions#new'
  post 'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get '/words/new' => 'words#new'

  get "/auth/google/callback" => 'sessions#create'
  get "/auth/failure" => redirect('/')  ##, to:
  get "/users/user_with_most_words" => 'users#user_with_most_words'

  resources :users do
    resources :words, only: [:index, :new, :create, :show]
  end
  resources :words do
    resources :word_feelings, only: [:new, :create]
  end
  resources :words, only: [:index, :show]
  resources :feelings, only: [:index, :show]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>loaded language</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= yield(:head) %>
  </head>
  <body>

    <!-- content -->
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <li class="navbar-brand">
        <%=link_to('Loaded Language', root_path)%>
        </li>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%=link_to "Words", words_path, class: "nav-link"%>
              </li>
              <li class="nav-item">
              <%=link_to "8 Emotions", feelings_path, class: "nav-link"%>
              </li>
            <% if logged_in?%>
              <li class="nav-item">
              <%=link_to "Add New Word", new_user_word_path(current_user.id), class: "nav-link"%>
              </li>
              <li class="nav-item">
              <%= link_to "My Info", user_url(current_user.id), class: "nav-link"%>
              </li>
              <li class="nav-item">
              <%= link_to "Log Out", logout_path, method: :delete, class: "nav-link"%>
              </li>
            <%else%>
              <li class="nav-item nav-link">
              <%= link_to('Log in', login_path) %> or <%= link_to('Sign up', signup_path)%><br>
              </li>
            <%end%>
          </ul>
        </div>
      </nav>

      <div class="container"  role="main">
        <%= yield %>
      </div>

      <!-- commented out, being called twice.
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
      -->
  </body>
</html>